---
engines:
  rubocop:
    enabled: true
    channel: "rubocop-0-87"
  bundler-audit:
    enabled: true
  brakeman:
    enabled: true
ratings:
  paths:
  - app/**
  - lib/**
  - "*.rb"
exclude_paths:
- app/assets/images/*
- config/**/*
- db/**/*
- spec/**/*
- vendor/**/*
- .*
- Gemfile*
- Rakefile
- startup.sh
- CHANGELOG.md
- CONTRIBUTING.md
- LICENCE.md
- README.md
- jenkins.sh
