version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    environment:
      - GOVUK_APP_DOMAIN: test
    steps:
      - checkout
      - run:
          name: Install System Dependencies
          command: sudo apt-get update -qq && sudo apt-get install -y build-essential nodejs rake
      - run:
          name: Install 'phantomjs'
          command: |
            sudo curl --output /tmp/phantomjs https://s3.amazonaws.com/circle-downloads/phantomjs-2.1.1
            sudo chmod ugo+x /tmp/phantomjs
            sudo ln -sf /tmp/phantomjs /usr/local/bin/phantomjs
      - run:
          name: Install bundler
          command: gem install bundler
      - run:
          name: Install gems
          command: bundle install
      - run:
          name: "Run Rspec"
          command: |
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out test_results/rspec.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - deploy:
          command: |
            curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
            sudo dpkg -i cf-cli_amd64.deb
            cf -v
      - deploy:
          command: |
            curl -v -L -o autopilot https://github.com/contraband/autopilot/releases/download/0.0.3/autopilot-linux
            chmod +x autopilot
            cf install-plugin autopilot -f
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ];
              then CF_SPACE=development CF_APP=tariff-frontend-dev CF_APP_WORKER=tariff-frontend-worker-dev ./bin/deploy
            fi
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "staging" ];
              then CF_SPACE=staging CF_APP=tariff-frontend-staging CF_APP_WORKER=tariff-frontend-worker-staging ./bin/deploy
            fi
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "production" ];
              then CF_SPACE=production CF_APP=tariff-frontend-production CF_APP_WORKER=tariff-frontend-worker-production ./bin/deploy
            fi
